---
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  SAST_EXCLUDED_ANALYZERS: "eslint,nodejs-scan"

include:
  - project: templates/ci
    file: DockerInDockerTemplate.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - >
      docker build --build-arg VERSION=$VERSION --build-arg SHOP_URL=$SHOP_URL --tag
      $CI_REGISTRY_IMAGE/momo-frontend:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE/momo-frontend:$CI_COMMIT_SHA

sonarqube-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner -Dsonar.projectKey=${SONAR_FRONTEND_PROJECT_KEY}
      -Dsonar.projectName=${SONAR_FRONTEND_PROJECT_NAME}
      -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.sources=.
      -Dsonar.login=${SONAR_LOGIN}
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  needs:
    - build

upload:
  stage: release
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/momo-frontend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/momo-frontend:$CI_COMMIT_SHA
      $CI_REGISTRY_IMAGE/momo-frontend:latest
    - docker push $CI_REGISTRY_IMAGE/momo-frontend:latest
  needs:
    - build

deploy:
  stage: deploy
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${DEV_USER}@${SHOP_URL}
      "export "VERSION=${VERSION}";
      export "REGISTRY_ACCESS_TOKEN=${REGISTRY_ACCESS_TOKEN}";
      export "REGISTRY_USER=${REGISTRY_USER}";
      /bin/bash -s " < ./deploy-frontend.sh
  environment:
    name: staging
    url: https://${SHOP_URL}
  when: manual
