version: '3.7'

services:
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-013-59/momo-store/momo-frontend:latest
    restart: always
    container_name: momo-frontend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl
    ports:
      - '80:80'
      - '8080:8080'
  backend:
    image: gitlab.praktikum-services.ru:5050/std-013-59/momo-store/momo-backend:latest
    restart: always
    container_name: momo-backend
    environment:
      VIRTUAL_HOST: momo-backend
      VIRTUAL_PORT: 8081
